name: Build

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - "**/*.md"
      - "CODEOWNERS"
      - "Makefile"
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - "**/*.md"
      - "CODEOWNERS"
      - "Makefile"

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          
      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command
      - name: Build production bundle
        uses: borales/actions-yarn@v4
        with:
          cmd: build:prod # will run `yarn build:prod` command
